export const SET_TOKEN = "SET_TOKEN"
export const SET_EMAIL = "SET_EMAIL"
export const SET_PASSWORD = "SET_PASSWORD"
export const SET_DOMAIN = "SET_DOMAIN"
export const REMOVE_TOKEN = "REMOVE_TOKEN"
export const REMOVE_EMAIL = "REMOVE_EMAIL"
export const REMOVE_PASSWORD = "REMOVE_PASSWORD"
export const REMOVE_DOMAIN = "REMOVE_DOMAIN"

export const SET_USER = "SET_USER"
export const REMOVE_USER = "REMOVE_USER"

export const LOADING = "LOADING"

export const MESSAGE = "MESSAGE"
export const SHOW_MESSAGE = "SHOW_MESSAGE"

export const SET_CLIENTS = "SET_CLIENTS"
export const SELECT_CLIENT = "SELECT_CLIENT"
export const REMOVE_CLIENTS = "REMOVE_CLIENTS"
export const UNSELECT_CLIENT = "UNSELECT_CLIENT"

export const SET_SESSIONS = "SET_SESSIONS"
export const REMOVE_SESSIONS = "REMOVE_SESSIONS"
export const SELECT_SESSIONS = "SELECT_SESSIONS"
export const UNSELECT_SESSION = "UNSELECT_SESSION"
export const SET_COUNTERS = "SET_COUNTERS"
export const SELECT_COUNTER = "SELECT_COUNTER"
export const UNSELECT_COUNTER = "UNSELECT_COUNTER"
export const REMOVE_COUNTERS = "REMOVE_COUNTERS"
export const SELECT_INSTANCE = "SELECT_INSTANCE"

export const SET_DATE = "SET_DATE"

export const SET_SIGNATURE = "SET_SIGNATURE"
export const SET_CLIENT_SIGNATURE = "SET_CLIENT_SIGNATURE"
export const REMOVE_SIGNATURE = "REMOVE_SIGNATURE"
